### ISSUE TITLE
Meeting Notes 23/10/2022

### ISSUE THREAD

**Issue by ms3744** [UTokyo-PBL/pbl2022-2022-team6#1]
# Meeting Notes - Sprint Planning
**Date:** 23/10/2022

**Time:** 10 AM (10:00)

**Attending:** @ms3744 @gaurishg @likunsheng @nnaakkaaii Rodrigo Curiel

### Agenda

1. Project Set Up
2. Tasks Delegation: FE | BE | DB | ML
3. Define Deliverables for the week

### Tasks
- [x] ALL - Learn UML Use Case Models and Templates Product Documents 
- [x] ALL - Learn Plant UML
- [x] ALL - Learn Terraform
- [x] Rodrigo & @ms3744 - Learning Figma
- [x] Rodrigo - Add tasks to Trello
- [x] @ms3744 - Add learning resources

### Sprint Goals
- [x] Rodrigo - Join team from GitHub Classroom
- [x] Rodrigo & @ms3744 - Define color scheme and UI/UX design
- [x] Rodrigo & @ms3744 - Conduct Usability Testing of Prototype Screens (depends above)
- [ ] @nnaakkaaii & @likunsheng - Template for Design Docs + ER Diagram
- [x] @nnaakkaaii & @likunsheng - Determine OpenAPI Schemas (depends above)
- [ ] @likunsheng & @nnaakkaaii  - Write Terraform (depends on template)
- [x] @gaurishg - Conduct Market Research
- [x] @gaurishg & @ms3744 - Creating Product Requirement Document
- [x] @gaurishg & @ms3744 - Develop Use Case Models for the project
- [x] @gaurishg - Find Pre-Trained Models and APIs (Object Detection, OCR, Translation)

**Next Meeting:** 28/10/2022 1 PM (13:00)
