### ISSUE TITLE
Meeting Notes - 09/12/2022

### ISSUE THREAD

**Issue by ms3744** [UTokyo-PBL/pbl2022-2022-team6#10]
# Meeting Notes - Sprint Planning
**Date:** 02/12/2022

**Time:** 1 PM (13:00)

**Attending:** @gaurishg @likunsheng @ccurielrodrigo @ms3744 @nnaakkaaii 

### Agenda

1. Sprint Review
2. Define Deliverables for the sprint and week

### Discussion Points
- The end points for object detection and location information
- Discussion of end-point document for back-end
- (Change in UI/UX) - Not displaying flag
- Testing the test AXIOS function
- Testing the Log in / Sign Up from FE to BE via Axios

### Tasks
FE:
- [x] @ms3744 @gaurishg - Decide to keep or not keep flag icons
- [ ] @ms3744 - Finish map screen to get what geocoding data we need
- [ ] @ms3744 @nnaakkaaii @likunsheng @gaurishg - Test the connection from FE to BE (check database connection and file storage) on Sunday Meeting
- [ ] @ms3744 @gaurishg - Object Detection Page | Text Detection Page | Text Translation Page | Home Map

Middle-End:
- [x] @nnaakkaaii @ms3744 - Complete Text Translation Module

BE:
- [x] @nnaakkaaii - Encrypt the password
- [x] @likunsheng - ask professor about the user and access keys 

ML:
- [x] @gaurishg - Python code for object detection (object + bounding box)

### Sprint Goals
- [ ] @ms3744 @gaurishg - Integrate most important features as FE
- [x] @ccurielrodrigo - Complete connecitons between FE and BE 
- [ ] @likunsheng - Complete Infrastructures on AWS and GCP
- [ ] @nnaakkaaii - Integrate BE with the ML and FE

**Next Meeting:** 11/12/2022 6 PM (18:00)
