### ISSUE TITLE
Meeting Notes - 16/12/2022

### ISSUE THREAD

**Issue by ms3744** [UTokyo-PBL/pbl2022-2022-team6#13]
# Meeting Notes - Sprint Review and Retrospection
**Date:** 16/12/2022

**Time:** 1 PM (13:00)

**Attending:** @likunsheng @ccurielrodrigo @ms3744 @nnaakkaaii 

### Agenda

1. Sprint Review
2. Define Deliverables for the sprint and week

### Discussion Points
- Connection of end points for object detection and location information between Python and the BE
- Discussion of end-point for anonymous user

### Tasks
FE:
- [x] @ms3744 - Finish map screen to get what geocoding data we need
- [x] @ms3744 - Remove / Update Image resizer (compression)
- [ ] @ms3744 @gaurishg - Object Detection Page | Text Detection Page | Text Translation Page | Home Map

Middle-End:
- [x] @nnaakkaaii @ccurielrodrigo - Adding Endpoint for the anonymous user

BE:
- [] @nnaakkaaii @gaurishg  - Real Model Implementation (Substitute fake translation client with real)
- [] @likunsheng - Add SSL

Presentation:
- [] @ccurielrodrigo - Begin with the presentation

### Sprint Goals
- [ ] @ms3744 @gaurishg - Integrate most important features as FE
- [x] @ccurielrodrigo - Complete connecitons between FE and BE 
- [ ] @likunsheng - Complete Infrastructures on AWS and GCP
- [ ] @nnaakkaaii - Integrate BE with the ML and FE

**Next Meeting:** 23/12/2022 1 PM (13:00)
