### ISSUE TITLE
Meeting Notes - 23/12/2022

### ISSUE THREAD

**Issue by ms3744** [UTokyo-PBL/pbl2022-2022-team6#14]
# Meeting Notes - Half way Sprint Review and Retrospection
**Date:** 16/12/2022

**Time:** 1 PM (13:00)

**Attending:** @likunsheng @gaurishg @ms3744 @nnaakkaaii 

### Agenda

1. Sprint Review
2. Define Deliverables for the sprint and week

### Discussion Points
- Screen Issues fixing
- Connection of end points for object detection and location information between Python and the BE
- Discussion of end-point for anonymous user

### Tasks
- [ ] @gaurishg @ms3744 - Translations for the text across all screens
- [ ] @ms3744 @gaurishg - Linking the flow of the screens
- [x] @ms3744 - Cleaned the sign up pages
- [ ] @ms3744 - Add languages to the translate (depends on Get Language end point)
- [x] @ms3744  - Correct Sign in page
- [ ] @gaurishg - Component for the user
- [x] @ms3744 - Finish home map screen (clean up and design conflicts)
- [ ] @ms3744 @gaurishg - Add buttons to navigate to previous pages 
- [x] @ms3744 - Game screens
- [ ] @ms3744 @gaurishg - Object Detection Page | Text Detection Page | Text Translation Page | Home Map

Middle-End:
- [x] @nnaakkaaii @ccurielrodrigo - Adding Endpoint for the anonymous user

BE:
- [ ] @nnaakkaaii @gaurishg  - Convert the get end points to post end points
- [ ] @gaurishg @nnaakkaaii - create "Get Languages" end point
- [x] @likunsheng - Add SSL

Presentation:
- [x] @ccurielrodrigo - Begin with the presentation
- [ ] @ccurielrodrigo @ms3744 - Adding a wiki 

ML:
- [ ] @gaurishg - OCR end point

### Sprint Goals
- [ ] @ms3744 @gaurishg - Integrate most important features as FE
- [x] @ccurielrodrigo - Complete connections between FE and BE 
- [ ] @likunsheng - Complete Infrastructures on AWS and GCP
- [ ] @nnaakkaaii - Integrate BE with the ML and FE

**Next Meeting:** 6/1/2023 1 PM (13:00)

**Comment by ms3744** [comment]
TODO:

- [ ] Upload test images with some latitude and longitude information for home screen
- [ ] Choose language for quiz based on the Get Language API
- [ ] Add scores to the API
