### ISSUE TITLE
Meeting Notes - 06/01/2023

### ISSUE THREAD

**Issue by ms3744** [UTokyo-PBL/pbl2022-2022-team6#15]
# Meeting Notes - Final Sprint Review and Retrospection
**Date:** 06/01/2023

**Time:** 3 PM (15:00)

**Attending:** @likunsheng @gaurishg @ms3744 @nnaakkaaii @ccurielrodrigo 

### Agenda

1. Sprint Review
2. Final project submission notes
3. Testing completion of functionalities

### Discussion Points
- Screen Issues fixing
- We are sending random location on the map with the data (show our features + protect the users)
- Discussing the flow of the presentation

### Tasks
FE:
- [x] @gaurishg @ms3744 - We send random location with map on data
- [x] @gaurishg @ms3744 - Link the nav bar buttons
- [x] @ms3744 @gaurishg - Dashboard is incomplete
- [ ] @ms3744 @gaurishg - Link Sign Up buttons
- [x] @ms3744 - Clean up the screens for the quiz 

Presentation:
- [ ] @ccurielrodrigo - Presentation edits
- [ ] @ccurielrodrigo - Template for the script
