### ISSUE TITLE
Meeting Notes 28/10/2022

### ISSUE THREAD

**Issue by ms3744** [UTokyo-PBL/pbl2022-2022-team6#2]
# Meeting Notes - Half-Way Sprint Review
**Date:** 28/10/2022

**Time:** 1 PM (13:00)

**Attending:** @ms3744 @gaurishg @likunsheng @nnaakkaaii @ccurielrodrigo 

**Duration:** 1 h 20 m

### Agenda

1. Discuss Project Progress
2. Tasks Delegation: FE | BE | DB | ML
3. Define Deliverables for the week

### Tasks
- [x] @ms3744 - Change Screen Layout to have Home first
- [x] @ccurielrodrigo - Add new tasks to Trello Board
- [ ] @nnaakkaaii @likunsheng - Define the data flow 
- [x] @ccurielrodrigo @ms3744  - Design UI/UX for prototype
- [x] @ccurielrodrigo @ms3744 - Ask Professor Regarding Approval for Usability Test
- [ ] @nnaakkaaii & @likunsheng - Template for Design Docs + ER Diagram
- [ ] @nnaakkaaii & @likunsheng - Determine OpenAPI Schemas (depends above)
- [ ] @likunsheng & @nnaakkaaii  - Write Terraform (depends on template)
- [ ] @gaurishg @ms3744 - Refine Product Functionalities
- [ ] @gaurishg - Add Flash Card Functionality
- [ ] @gaurishg - Upload files to the drive
- [ ] @gaurishg @ms3744 - Develop Use Case Model
- [ ] @gaurishg - Find Pre-Trained Models and APIs (Object Detection, OCR, Translation)

**Next Meeting:** 04/11/2022 1 PM (13:00)
