### ISSUE TITLE
Meeting Notes 04/11/2022

### ISSUE THREAD

**Issue by ms3744** [UTokyo-PBL/pbl2022-2022-team6#4]
# Meeting Notes - Sprint Planning
**Date:** 04/11/2022

**Time:** 1 PM (13:00)

**Attending:** @ms3744 @gaurishg @likunsheng @nnaakkaaii @ccurielrodrigo 

### Agenda

1. Sprint Review and Retrospect
2. Sprint Planning
3. Tasks Delegation: FE | BE | DB | ML
4. Define Deliverables for the week

### Discussion Points
- [ ] Translated text history will be changed to an optional requirement
- [ ] Categorization of the images as an optional requirement
- [ ] Translations do not need the log in feature anymore
- [ ] Check UI color scheme 
- [ ] For geolocation in the usability testing - Ensure that the details will be deleted / not taken and ensure that this information is available in the documentation accompanying the test
- [ ] The password will be encrypted in the back end
- [ ] Alternative texts can be stored in an array
- [ ] Google translate API for OCR + Translate

### Tasks
- [ ] @gaurishg - Research about text to speech 
- [x] @ms3744 @ccurielrodrigo - Add upload screen to the UI
- [x] @ccurielrodrigo - Email professor regarding usability testing
- [ ] @gaurishg - Research about the bounding boxes for the text
- [ ] @nnaakkaaii @likunsheng - Finish Terraform code
- [ ] @ms3744 - Research if we can restrict functionalities for the web 
- [x] @ms3744 - Research for a plug in from Figma to HTML/CSS
- [x] @ccurielrodrigo - Make any changes in the Trello board

### Sprint Goals
- [x] @ccurielrodrigo & @ms3744 - Finish the prototype screens
- [ ] @gaurishg  & @ms3744 - Start up the front end
- [ ] @nnaakkaaii & @likunsheng - Template for Design Docs + ER Diagram
- [ ] @likunsheng & @nnaakkaaii  - Write Terraform (depends on template)
- [ ] @gaurishg @likunsheng @nnaakkaaii - Feasibility testing on the APIs (Check phonetical + language alphabets)
- [x] @ccurielrodrigo @ms3744 - Add website prototype screens to the Figma

**Next Meeting:** 11/11/2022 1 PM (13:00)
