### ISSUE TITLE
Meeting Notes - 11/11/2022

### ISSUE THREAD

**Issue by ms3744** [UTokyo-PBL/pbl2022-2022-team6#5]
# Meeting Notes - Sprint Planning
**Date:** 11/11/2022

**Time:** 2 PM (14:00)

**Attending:** @ms3744 @gaurishg @likunsheng @nnaakkaaii @ccurielrodrigo 

### Agenda

1. Sprint Half-way Review
2. Define Deliverables for the week

### Discussion Points
- Object Detection and Text Detection will be separate API calls but the image will get uploaded on the server only once
- Audio and Translations can be cached in the server after the first request
- Object ID + Translate Language + Translation + Voice URL can be stored in the server for Object Detection
- Adding a filter on the list of flash cards for the number of cards per game
- Currently, not working on lists for now

### Tasks
-[ ] @likunsheng @nnaakkaaii - Check what going on with @nnaakkaaii with sprint 2 cards (green)
- [ ] @gaurishg - Finish the market research
- [ ] @ms3744 @gaurishg - Continue to work on the front end
- [ ] @gaurishg - Convert model output to text
- [x] @ms3744 @ccurielrodrigo - Define algorythm for text bounding boxes 
- [ ] @likunsheng - Update the code for the latest changes on the requirements
- [x] @ccurielrodrigo - Send entrypoint lists

### Sprint Goals
- [ ] @ms3744 @gaurishg - Front end template (unify styles)
- [ ] @likunsheng @nnaakkaaii @gaurishg - Backend alfa 1 (login / signup / password recovery / basic object recognition <optimistic, but lovely if possible>)

**Next Meeting:** 18/11/2022 1 PM (13:00)
