### ISSUE TITLE
Meeting Notes - 18/11/2022

### ISSUE THREAD

**Issue by ccurielrodrigo** [UTokyo-PBL/pbl2022-2022-team6#6]
# Meeting Notes - Sprint Planning
**Date:** 18/11/2022

**Time:** 1 PM (13:00)

**Attending:** @gaurishg @likunsheng @ccurielrodrigo 

### Agenda

1. Sprint Review
2. Define Deliverables for the sprint and week

### Discussion Points
- Showcase of the finished prototype
- Issues with Megha's and Gaurish's versions of the front end template
- Nakai and Kungsheng are nearly finishing the BE templates
- Information flow of the translation from object to text
- Text to speech is an independent API to consider
- Starting of the development of actual Backend and Frontend
- Unifying development styles of both front and back ends

### Tasks
- [ ] @likunsheng @nnaakkaaii - Check what going on with @nnaakkaaii with sprint 2 cards (green)
- [ ] @gaurishg - Finish the market research
- [ ] @ms3744 @gaurishg - Continue to work on the front end
- [ ] @gaurishg - Convert model output to text
- [ ] @ms3744 @ccurielrodrigo - Define algorythm for text bounding boxes 
- [ ] @likunsheng - Update the code for the latest changes on the requirements
- [ ] @ccurielrodrigo - Send entrypoint lists
- [ ] @ccurielrodrigo - Make an outline of the database

### Sprint Goals
- [ ] @ms3744 @gaurishg @ccurielrodrigo - Front end template (unify styles)
- [ ] @likunsheng @nnaakkaaii @gaurishg - Backend alfa 1 (login / signup / password recovery / basic object recognition <optimistic, but lovely if possible>)

**Next Meeting:** 25/11/2022 1 PM (13:00)
