### ISSUE TITLE
Meeting Notes - 25/11/2022

### ISSUE THREAD

**Issue by ms3744** [UTokyo-PBL/pbl2022-2022-team6#7]
# Meeting Notes - Sprint Planning
**Date:** 25/11/2022

**Time:** 1 PM (13:00)

**Attending:** @gaurishg @likunsheng @ccurielrodrigo @ms3744 @nnaakkaaii 

### Agenda

1. Sprint Review
2. Define Deliverables for the sprint and week

### Discussion Points
- The AWS is not working as expected with professor - Resolved
- Discussion of end-point document for back-end
- (Optional Requirement) - Newsletter Enrolment
- (Optional Requirement) - 2-step Authentication Log-in

### Tasks
- [ ] @nnaakkaaii - Create database
- [ ] @likunsheng - AWS Resources
- [ ] @ms3744 @gaurishg - Code the most important components
- [ ] @ccurielrodrigo - Work on the middle-end
- [ ] @nnaakkaaii @ms3744 - Test the Go-lang Tensor flow API call
- [ ] @ms3744 @gaurishg - Try to run the Map API on the front-end 

### Sprint Goals
- [ ] @ms3744 @gaurishg @ccurielrodrigo - Front end template (unify styles)
- [ ] @likunsheng @nnaakkaaii @gaurishg - Backend alfa 1 (login / signup / password recovery / basic object recognition <optimistic, but lovely if possible>)

**Next Meeting:** 2/12/2022 1 PM (13:00)
