### ISSUE TITLE
Meeting Notes - 02/12/2022

### ISSUE THREAD

**Issue by ms3744** [UTokyo-PBL/pbl2022-2022-team6#9]
# Meeting Notes - Sprint Planning
**Date:** 02/12/2022

**Time:** 1 PM (13:00)

**Attending:** @gaurishg @likunsheng @ccurielrodrigo @ms3744 @nnaakkaaii 

### Agenda

1. Sprint Review
2. Define Deliverables for the sprint and week

### Discussion Points
- The AWS is not working as expected with professor - Resolved
- Discussion of end-point document for back-end
- (Optional Requirement) - Newsletter Enrolment
- (Optional Requirement) - 2-step Authentication Log-in

### Tasks
FE:
- [x] @ms3744 - compressing image
- [ ] @gaurishg - Encrypt the password
- [ ] @ms3744 @gaurishg - Object Detection Page | Text Detection Page | Text Translation Page | Home Map
- [x] @ms3744 - Check out react text to speech

Middle-End:
- [ ] @nnaakkaaii @ms3744 - Add Text Translation Module
- [x] @nnaakkaaii @ccurielrodrigo - Discuss the changes between the openAPI and AXIOS code

BE:
- [ ] @likunsheng - ask professor about the user and access keys
- [ ] @likunsheng - set up terraform for GCP, and send Translation API key + Text-to-speech API Key to @nnaakkaaii and @ms3744 

ML:
- [ ] @gaurishg - Python code for object detection (object + bounding box)

### Sprint Goals
- [ ] @ms3744 @gaurishg - Integrate most important features as FE
- [x] @ccurielrodrigo - Complete connecitons between FE and BE 
- [ ] @likunsheng - Complete Infrastructures on AWS and GCP
- [ ] @nnaakkaaii - Integrate BE with the ML and FE

**Next Meeting:** 9/12/2022 1 PM (13:00)
